
      common /bsply1/
     +        grdy(mxx0,2),jtfy(mxx0,2),minby(mxx0,2),maxby(mxx0,2),
     +        nny(2),kky(2)      
      common /bsply2/
     +        tauy(mxx0,2),iyft(mxx0,2),icaty(mxx0,2),nty(2)
      common /bsply3/
     +        caty(iom0,iom0,mxx0,2),ncy(2) 

      common /bsplq1/
     +        grdq(mqq0),jtfq(mqq0),minbq(mqq0),maxbq(mqq0),nnq,kkq
      common /bsplq2/
     +        tauq(mqq0),iqft(mqq0),icatq(mqq0),ntq
      common /bsplq3/
     +        catq(iom0,iom0,mqq0),ncq 
