      logical Lygrid2, Ltgrid2
      common /yygrid/ ygrid2(0:mxx0),ymin2(0:mxg0),ymax2(0:mxg0),
     &                dely2(0:mxg0) ,nyy2(0:mxg0) ,
     &                iyma2(mxg0)   ,iwgt2(mxg0)  ,
     &                iaoff2(mxg0)  ,ioy2, nyg2, nstory2
      common /yygnew/ iy0fiyg2(0:mxx0,mxg0), jymi2(mxg0)
      common /yysmat/ smaty2(mxx0), sinvy2(mxx0), nmaty2, ninvy2
      common /ttgrid/ tgrid2(mqq0), ntt2
      common /zzgrid/ zgrid2(mqq0+7),itfiz2(mqq0+7),izfit2(mqq0+7),
     &                nffiz2(mqq0+7),nzz2
      common /ttresh/ itchm2, itbot2, ittop2
      common /grdflg/ Lygrid2, Ltgrid2
      common /evcuts/ xminc2,xmaxc2,qminc2,qmaxc2,smaxc2,ascut2,
     &                ymaxc2,tminc2,tmaxc2 
      common /evlims/ iymac2,izmic2,izmac2,ismac2(mqq0)



      



